
CREATE TABLE CommunityArea
(
    ID INT,
    name CHAR(32),
    side CHAR(32)
);

INSERT INTO CommunityArea(
    ID,
    name,
    side
)
VALUES
    (1,'Rogers Park','Far North side'),
    (2,'West Ridge','Far North side'),
    (3,'Uptown','Far North side'),
    (4,'Lincoln Square','Far North side'),
    (5,'North Center','North Side'),
    (6,'Lake View','North Side'),
    (7,'Lincoln Park','North Side'),
    (8,'Near North Side','Central'),
    (9,'Edison Park','Far North side'),
    (10,'Norwood Park','Far North side'),
    (11,'Jefferson Park','Far North side'),
    (12,'Forest Glen','Far North side'),
    (13,'North Park','Far North side'),
    (14,'Albany Park','Far North side'),
    (15,'Portage Park','Northwest side'),
    (16,'Irving Park','Northwest side'),
    (17,'Dunning','Northwest side'),
    (18,'Montclare','Northwest side'),
    (19,'Belmont Cragin','Northwest side'),
    (20,'Hermosa','Northwest side'),
    (21,'Avondale','North Side'),
    (22,'Logan Square','North Side'),
    (23,'Humboldt Park','West Side'),
    (24,'West Town','West Side'),
    (25,'Austin','West Side'),
    (26,'West Garfield Park','West Side'),
    (27,'East Garfield Park','West Side'),
    (28,'Near West Side','West Side'),
    (29,'North Lawndale','West Side'),
    (30,'South Lawndale','West Side'),
    (31,'Lower West Side','West Side'),
    (32,'Loop','Central'),
    (33,'Near South Side','Central'),
    (34,'Armour Square','South Side'),
    (35,'Douglas','South Side'),
    (36,'Oakland','South Side'),
    (37,'Fuller Park','South Side'),
    (38,'Grand Boulevard','South Side'),
    (39,'Kenwood','South Side'),
    (40,'Washington Park','South Side'),
    (41,'Hyde Park','South Side'),
    (42,'Woodlawn','South Side'),
    (43,'South Shore','South Side'),
    (44,'Chatham','Far Southeast side'),
    (45,'Avalon Park','Far Southeast side'),
    (46,'South Chicago','Far Southeast side'),
    (47,'Burnside','Far Southeast side'),
    (48,'Calumet Heights','Far Southeast side'),
    (49,'Roseland','Far Southeast side'),
    (50,'Pullman','Far Southeast side'),
    (51,'South Deering','Far Southeast side'),
    (52,'East Side','Far Southeast side'),
    (53,'West Pullman','Far Southeast side'),
    (54,'Riverdale','Far Southeast side'),
    (55,'Hegewisch','Far Southeast side'),
    (56,'Garfield Ridge','Southwest side'),
    (57,'Archer Heights','Southwest side'),
    (58,'Brighton Park','Southwest side'),
    (59,'McKinley Park','Southwest side'),
    (60,'Bridgeport','South Side'),
    (61,'New City','Southwest side'),
    (62,'West Elsdon','Southwest side'),
    (63,'Gage Park','Southwest side'),
    (64,'Clearing','Southwest side'),
    (65,'West Lawn','Southwest side'),
    (66,'Chicago Lawn','Southwest side'),
    (67,'West Englewood','Southwest side'),
    (68,'Englewood','Southwest side'),
    (69,'Greater Grand Crossing','South Side'),
    (70,'Ashburn','Far Southwest side'),
    (71,'Auburn Gresham','Far Southwest side'),
    (72,'Beverly','Far Southwest side'),
    (73,'Washington Heights','Far Southwest side'),
    (74,'Mount Greenwood','Far Southwest side'),
    (75,'Morgan Park','Far Southwest side'),
    (76,'OHare','Far North side'),
    (77,'Edgewater','Far North side');